>>> matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

>>> matrix_mul("Hello", [[1,2,3],[4,5,6]])
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> matrix_mul([[1,2,3],[4,5,6]], "Julien")
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> matrix_mul(["Alx", "Julien"],[[1,2],[3,4]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> matrix_mul([[1,2],[3,4]], ["Alx","Julien"])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> matrix_mul([], [[1,2],[3,4]])
Traceback (most recent call last):
ValueError: shapes (0,) and (2,2) not aligned: 0 (dim 0) != 2 (dim 0)

>>> matrix_mul([[]], [[1,2],[3,4]])
Traceback (most recent call last):
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

>>> matrix_mul([[1,2],[3,4]], [])
Traceback (most recent call last):
ValueError: shapes (2,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)

>>> matrix_mul([[1,2],[3,4]], [[]])
Traceback (most recent call last):
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> matrix_mul([[1,2],[3,'a']],[[1,2],[3,4]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> matrix_mul([[1,2],[3,4]], [[1,'a'], [2,3]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> matrix_mul([[1,2,3],[4,5]], [[1,2], [3,4]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> matrix_mul([[1,2],[3,4]], [[1,2,3],[4,5]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
